const sections = [
  {
    title: "Acceptance of terms",
    body: `By creating an account or using Dadima, you agree to these Terms of Service. If you do not agree, please do not use the service. These terms apply to all users, including free and paid subscribers.`,
  },
  {
    title: "Description of service",
    body: `Dadima is an AI-powered bedtime story generation service. We generate personalized children's stories based on the name, age, language, and theme you provide. Stories are generated using large language model technology and may occasionally contain imperfections. We do not guarantee that every story will be perfectly tailored or free of minor errors.`,
  },
  {
    title: "User accounts",
    body: `You must be at least 18 years old to create a Dadima account. You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. Notify us immediately at hello@dadima.app if you suspect unauthorized access.`,
  },
  {
    title: "Free and paid plans",
    body: `The Free plan includes 3 story generations per month at no charge. Paid plans (Premium and Family) unlock additional features as described on our Pricing page. Paid subscriptions are billed monthly and renew automatically unless cancelled before the renewal date. Prices are in Indian Rupees (INR) and include applicable taxes.`,
  },
  {
    title: "Acceptable use",
    body: `You agree to use Dadima only for its intended purpose: generating children's stories for personal, non-commercial use. You may not use Dadima to generate content that is harmful, abusive, or inappropriate for children; attempt to reverse-engineer or scrape our AI models; resell or redistribute generated stories commercially; or impersonate another person or entity.`,
  },
  {
    title: "Intellectual property",
    body: `Stories generated by Dadima are provided to you for personal use. You own the stories generated for your account and may print, save, or share them freely for personal use. Dadima retains rights to the underlying model, software, and platform. The Dadima name, logo, and design are our trademarks and may not be used without permission.`,
  },
  {
    title: "Limitation of liability",
    body: `Dadima is provided "as is." We make no warranties about the accuracy, completeness, or suitability of generated stories. To the maximum extent permitted by law, Dadima shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability to you shall not exceed the amount you paid us in the 3 months prior to the claim.`,
  },
  {
    title: "Termination",
    body: `We reserve the right to suspend or terminate your account if you violate these terms. You may cancel your account at any time from your Account settings page. On cancellation, your paid subscription will remain active until the end of the current billing period.`,
  },
  {
    title: "Governing law",
    body: `These terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of Hyderabad, Telangana.`,
  },
];

export default function TermsPage() {
  return (
    <div style={{ background: "#FFFBF6", minHeight: "100vh", paddingTop: 80 }}>
      <div style={{ maxWidth: 760, margin: "0 auto", padding: "60px 32px" }}>
        <p style={{ fontSize: 12, fontWeight: 800, color: "#7C5CFC", letterSpacing: 2, textTransform: "uppercase", marginBottom: 12 }}>LEGAL</p>
        <h1 style={{ fontSize: "clamp(28px,4vw,44px)", fontWeight: 800, color: "#111827", letterSpacing: "-.03em", marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: "#9CA3AF", marginBottom: 48 }}>Last updated: June 25, 2026</p>

        <div style={{ display: "flex", flexDirection: "column", gap: 36 }}>
          {sections.map((s, i) => (
            <div key={s.title}>
              <h2 style={{ fontSize: 18, fontWeight: 800, color: "#111827", marginBottom: 12, display: "flex", alignItems: "center", gap: 10 }}>
                <span style={{ width: 28, height: 28, background: "#F5F3FF", borderRadius: 8, display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 800, color: "#7C5CFC", flexShrink: 0 }}>{i + 1}</span>
                {s.title}
              </h2>
              <p style={{ fontSize: 15, color: "#374151", lineHeight: 1.85 }}>{s.body}</p>
            </div>
          ))}
        </div>

        <div style={{ marginTop: 56, padding: "24px 28px", background: "#fff", border: "1.5px solid #ECECEC", borderRadius: 16 }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: "#111827", marginBottom: 4 }}>Questions about these terms?</div>
          <div style={{ fontSize: 14, color: "#6B7280" }}>Email us at <a href="mailto:hello@dadima.app" style={{ color: "#7C5CFC", textDecoration: "none" }}>hello@dadima.app</a></div>
        </div>
      </div>
    </div>
  );
}
